# Generated by Django 5.1.4 on 2024-12-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_options_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link_to_pay",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
    ]
