version: '3.9'

services:

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis_data:/data
    restart: on-failure
    expose:
      - "6379"

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - "5432"


  web:
    build: .
    command: bash -c "
      python manage.py migrate
      && python manage.py create_super_user
      && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=db



volumes:
  redis_data:
  postgres_data:
  static_volume: