# Generated by Django 5.1.3 on 2024-12-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Введите описание урока",
                max_length=255,
                null=True,
                verbose_name="Описание урока",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
